# message(STATUS ${CMAKE_HOST_SYSTEM_NAME} ${CMAKE_HOST_SYSTEM_VERSION}
# ${CMAKE_HOST_SYSTEM_PROCESSOR}) execute_process( COMMAND . /etc/os-release
# COMMAND echo "${ID,,}-$VERSION_ID" OUTPUT_VARIABLE DISTRO_VERSION
# OUTPUT_STRIP_TRAILING_WHITESPACE)

# cpack part include(InstallRequiredSystemLibraries)


set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VENDOR "ocp.toolkit")
set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${CMAKE_PROJECT_DESCRIPTION})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_FILE_NAME
    ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_HOST_SYSTEM_NAME})
set(CPACK_PACKAGE_CONTACT "support@opencax.plus")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_STRIP_FILES YES)
set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE ON)



# cpack part include(InstallRequiredSystemLibraries)
set(CPACK_SOURCE_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_SOURCE_PACKAGE_VENDOR "ocp.toolkit")
set(CPACK_SOURCE_PACKAGE_DESCRIPTION_SUMMARY ${CMAKE_PROJECT_DESCRIPTION})
set(CPACK_SOURCE_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_SOURCE_PACKAGE_FILE_NAME
    ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION})
set(CPACK_SOURCE_PACKAGE_CONTACT "support@opencax.plus")
set(CPACK_SOURCE_STRIP_FILES YES)
set(CPACK_SOURCE_IGNORE_FILES
    build/
    install/
    docs/
    .git/
    .github/
    ocp/
    .gitignore)



include(CPack)
