name: Toolkit Build
defaults:
  run:
    shell: bash -ileo pipefail {0}
on:
  workflow_dispatch:
    inputs:
      id:
        description: "Software id"
        required: true
        default: "ocptk"
      version:
        description: "Software version"
        required: true
        default: "1.11.0"
jobs:
  build:
    runs-on: ["self-hosted","cloud"]
    steps:
      - name: Basic info
        run: |
          echo "Build for ${{ github.ref }} branch in ${{ github.repository }} repository."
          echo "Job triggered by ${{ github.event_name }}, on self-hosted ${{ runner.os }}."
      - name: Check out repository
        uses: actions/checkout@v3
          # Option 2: specify 'latest' or 'latestrc' in the input version arguments:
      - name: Prepare and Install
        run: |
          source scripts/prepare.sh ${{ github.event.inputs.version }} ${{ github.event.inputs.id }}
          source ocp/toolkit/${{ github.event.inputs.id }}/${{ github.event.inputs.version }}/configurations/default.sh linux-gnu-Debug
